[package]
name = "hs-door-proxy"
version = "0.1.0"
authors = ["Tiago Nascimento <tiago.nascimento@spruceid.com>"]
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
sha2 = "0.9"
reqwest = { version = "0.11", features = ["blocking", "json"] }
hex = "0.4"
